# Generated by Django 3.2.5 on 2021-07-26 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.campeonato')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.rodada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'campeonato', 'rodada')},
            },
        ),
        migrations.CreateModel(
            name='ApostaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol_casa', models.IntegerField()),
                ('gol_visitante', models.IntegerField()),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aposta.aposta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.jogo')),
            ],
            options={
                'unique_together': {('aposta', 'jogo')},
            },
        ),
    ]
