# Generated by Django 3.2.5 on 2021-07-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temporada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('jogos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('gols_pro', models.IntegerField()),
                ('gols_contra', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.campeonato')),
                ('clube_casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clube_casa', to='clube.clube')),
                ('clube_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clube_visitante', to='clube.clube')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonato.rodada')),
            ],
            options={
                'unique_together': {('campeonato', 'clube_casa', 'clube_visitante')},
            },
        ),
    ]
