# Generated by Django 3.2.5 on 2021-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='clube',
            field=models.ManyToManyField(to='clube.Clube'),
        ),
    ]
